#!/bin/bash
export MAC=$(printf "%02x:%02x:%02x:%02x:%02x:%02x" $(( ($RANDOM * 4 + 2) % 256)) $(($RANDOM%256)) $(($RANDOM%256)) $(($RANDOM%256)) $(($RANDOM%256)) $(($RANDOM%256)))
qemu-system-x86_64 -enable-kvm -net tap -net nic,id=eth0,macaddr=$MAC -m 512 -boot n,strict=on "$@"
