#!/bin/bash
export MAC=$(printf "%02x:%02x:%02x:%02x:%02x:%02x" $(( ($RANDOM * 4 + 2) % 256)) $(($RANDOM%256)) $(($RANDOM%256)) $(($RANDOM%256)) $(($RANDOM%256)) $(($RANDOM%256)))
qemu-system-x86_64 -serial stdio -enable-kvm -net tap -net nic,id=eth0,macaddr=$MAC,model=virtio -m 512 -boot n,strict=on -uuid $(uuid -v 4) -monitor none -nographic "$@"
