#!/bin/bash
export MAC=$(printf "%02x" $((($RANDOM * 4 + 2) % 256)) $(($RANDOM%256)) $(($RANDOM%256)) $(($RANDOM%256)) $(($RANDOM%256)) $(($RANDOM%256)))
export HOSTNAME="sivtar-$MAC"
mount -t proc proc /proc 2>/dev/null

rootfstype=$(awk '{ if($2=="/") print $3 }' /proc/mounts)
rootmount=$(awk '{ if($2=="/") print $1 }' /proc/mounts)
server=${rootmount%%:*}
if ip -4 -o addr show dev eth0|grep eth0; then
    have_ipv4=1
fi

echo rootmount ${rootmount} server ${server}

# remount as nfs4 rather than nfs3
if [ "$rootfstype" == "nfs" ]; then
    mount -t nfs4 ${rootmount} /mnt/newroot
    mount -n --move /run /mnt/newroot/run
    mount -n --move /dev /mnt/newroot/dev
    pivot_root /mnt/newroot /mnt/newroot/mnt/root/oldroot
fi

mount -n -t tmpfs none /mnt/etc
mount -n -t tmpfs none /var/lib/dhcp
mount -n -t aufs -o rw -o noxino -o br:/mnt/etc:/etc aufs /etc
cat /etc/fstab.${rootfstype} | sed -e "s/^sivtar-server:/${server}:/" > /etc/fstab
if [ -z "${have_ipv4}" ]; then
    dhclient -v -6 -S eth0
    while [ -z "$ip" ]; do
	ip=$(ip -o -6 addr show dev eth0 scope global | awk '{ print $4 }')
	ip=${ip%%/*}
    done
fi
mount -n /mnt/roots
umount -n /etc

mkdir /mnt/roots/$HOSTNAME
mkdir /mnt/roots/$HOSTNAME/tmp
mkdir /mnt/roots/$HOSTNAME/tmptmp
mount -n -t tmpfs none /mnt/roots/$HOSTNAME/tmptmp
mount -n -t aufs -o rw -o xino=/mnt/roots/$HOSTNAME/tmptmp/.aufs.xino -o br:/mnt/roots/$HOSTNAME=rw+coo_all:/ aufs /mnt/newroot

mount -n --move /run /mnt/newroot/run
mount -n --move /dev /mnt/newroot/dev

echo "$HOSTNAME" > /mnt/newroot/etc/hostname
pivot_root /mnt/newroot /mnt/newroot/mnt/root/oldroot

cat /etc/fstab.${rootfstype} | sed -e "s/^sivtar-server:/${server}:/" > /etc/fstab

echo auto eth0 > /etc/network/interfaces.d/eth0
if [ -n "${have_ipv4}" ]; then
    echo iface eth0 inet dhcp >> /etc/network/interfaces.d/eth0
fi
echo iface eth0 inet6 manual >> /etc/network/interfaces.d/eth0

cd /

exec /sbin/init "$@"
